mode: standalone
env: dev
appName: talaria

storage:
  dir: "/data"

writers:
  grpc:
    port: 8080 # gRPC endpoint for ingesting events

readers:
  presto:
    schema: eventlog
    port: 8042 # Thrift port for Presto

tables:
  eventlog:
    name: eventlog
    schema: "file:////config/schema.yaml"
    ttl: 3600
    hashBy: event
    # compact:
    #   interval: 60
    #   s3: # sink to Amazon S3
    #     region: "us-east-1"
    #     prefix: "eventlog/"
    #     bucket: "data"
    #     endpoint: "http://minio:9000"
    #     accessKey: "adminadmin"
    #     secretKey: "adminadmin"
