mode: standalone
env: development
domain: "talaria:8042"

# Storage configuration
storage:
  dir: "/data"

# Writers - how data gets into Talaria
writers:
  grpc:
    port: 8080 # gRPC endpoint for ingesting events
  file:
    uri: "file:///data/output"

# Readers - how Presto queries Talaria
readers:
  presto:
    schema: data # Schema name in Presto
    port: 8042 # Thrift port for Presto

# Table definitions
tables:
  eventlog:
    ttl: 3600 # Keep data for 1 hour (in seconds)
    hashBy: event # Partition by event type
    sortBy: time # Sort by timestamp
    schema: data

    # Optional: Enable compaction to write to storage
    compact:
      interval: 60 # Compact every 60 seconds
      file: # Write to local filesystem
        dir: "/output/eventlog"

  # Add more tables as needed
  metrics:
    ttl: 7200 # Keep data for 2 hours
    hashBy: metric
    sortBy: time
    schema: data
    compact:
      interval: 120
      file:
        dir: "/output"
